### ISSUE TITLE
[BUG] Media Session Issues

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#102]
Thanks for the update it fixed a lot of problems and added so many new features, but there is still one that is the most important, when the track is paused I can't resume it from the notifications. Also, the "resume if was paused by interruption" option doesn't work, so anytime the track gets paused by an interruption and the interruption is finished, I want the track to resume but it doesn't. So I go to the notifications and try to resume it, but i can't do that, so I have to stop what I'm doing, open the namida app, resume the track, and then come back.

**Comment by z9xx7o0** [comment]
I see the "resume if was paused by volume" is working just fine. I don't know why the other one doesn't work. I am currently running oneUi 6.0, which is android 14, and I am on the Samsung Galaxy s23 ultra. Sorry, I don't know how to get the logs, but I hope that helps!

**Comment by MSOB7YY** [comment]
volume works cuz they are both handled differently, a listener just keeps listening to device volume and plays/pauses accordingly 

while the other one is managed internally by android media session token, i suspected at first that the other apps dont send back that they stopped playing, but it seems there is more than that

investigating will surely take time

---

about the play from notification issue, i highly doubt its due to android 14 shakalaka thingy, logs might be needed idk so try sharing it from "settings > about > share logs"
otherwise ill install android 14 emulator and check things, but later

**Comment by MSOB7YY** [comment]
@z9xx7o0 
as mentioned, 
- "**resume if was paused by interruption**" was fixed, and also introduced a logic to not resume if was paused for more than specific duration.
- notification play button is also fixed, it was an Android 14 specific issue

thanks for pointing these out
