### ISSUE TITLE
ISSUE app running in background too much.

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#110]
Namida has been running in the background for 27 hours straight even though I closed the app and dismissed the notification.
![Screenshot_20240113_111223_One UI Home.png](https://github.com/namidaco/namida/assets/83415416/0ce28d99-a5fc-44a1-885c-c92c17c3abe0)

**Comment by MSOB7YY** [comment]
since v1.9.2, service is getting killed once u dismiss notification, at this point it's up to android wether to kill namida or not if needed 
![Screenshot_20240113-140847_Settings](https://github.com/namidaco/namida/assets/85245079/82cafeae-7b29-4ef4-ae89-1ee76fa60e1a)

if you want to kill namida when closing app, check
`settings > playback > kill player after dismissing app`

otherwise if you manually locked namida that's an issue on ur side

**Comment by z9xx7o0** [comment]
Is it possible to kill the app when dismissing the notification? Or can you add this feature?
