### ISSUE TITLE
MP3 Tag Reading does not work correctly

### ISSUE THREAD

**Issue by CaptainKarma** [namidaco/namida#12]
Namida looks great but after scanning my 40k library its reporting I have 21 Albums, 9 Genres and the Artists screen doesn't function at all.

Let me know how I can help debug this.  I tried to fork it but there are lots of flutter dependencies that aren't available so I couldn't build it.

Thanks

![Screenshot_20231008-171559](https://github.com/namidaco/namida/assets/1750450/6c3a5feb-cc96-470a-a9dd-40c935157404)

**Comment by MSOB7YY** [comment]
thank you 🌺

1. since there are some albums and genres extracted, it means that the indexer is working fine, the issue is only with specific files
2. while indexing, if, for any reason, info couldn't be extracted, Namida tries to put title & artist from filename
3. artists in screenshot seems like they been extracted from filename
4. please share logs at `/storage/emulated/0/Android/data/com.msob7y.namida/files/logs.txt`
5. as for building, there are some libraries of mine made private, i dont want people stealing code for now, but they should be public if it ever got recognition, sorry for that

**Comment by CaptainKarma** [comment]
All my mp3 files are properly tagged with id3v2.3 and in a folder structure of artist/album/01 - filename.mp3

4.  Please find attached
5.  Sure ok, understood

Let me know if I can help further, thanks

[logs.txt](https://github.com/namidaco/namida/files/12841524/logs.txt)

**Comment by MSOB7YY** [comment]
@CaptainKarma 
uhmm the logs doesnt say much, im thinking about adding ffmpeg tag reading as a fallback but it takes longer than the native tagger, can u please send some samples (2-3) of the audio files on [telegram](https://t.me/+FmdfsgKoGmM1ZGFk) or on [discord](https://discord.com/invite/WeY7DTVChT) ? sorry for the inconvenience

**Comment by MSOB7YY** [comment]
ce481c787e2594d76bb03ca07d85cce00e1ec400 ffmpeg added as a fallback tag reader
- with some optimizations, performance is almost the same, at worst it might be 10% slower (due to separate artwork extraction) but overall this should fix it
