### ISSUE TITLE
Good concept, bad implementation 

### ISSUE THREAD

**Issue by Joeeeeb5** [namidaco/namida#17]
I get what the app is trying to be but it's cluttered with features. Don't get me wrong, some of them are useful and new but everything is everywhere on the screen, the app is laggy and janky while trying to look polished

**Comment by MSOB7YY** [comment]
u cant deny features because u cant use them, they exist for who need it, things are there if u needed while in the same time u can just ignore and literally just play music 
i don't get someone would hate more features :/

from my experience, i haven't encountered lag except while indexing only, which is normal, as someone who uses namida, i enjoy the experience without issues/lag

what are examples of features u cant use ?

**Comment by Joeeeeb5** [comment]
> u cant deny features because u cant use them, they exist for who need it, things are there if u needed while in the same time u can just ignore and literally just play music 
> i don't get someone would hate more features :/
> 
> from my experience, i haven't encountered lag except while indexing only, which is normal, as someone who uses namida, i enjoy the experience without issues/lag
> 
> what are examples of features u cant use ?

Video/audio switcher thingy, online caching, album art animation on/off and some other stuff i found in the app. I was bombarded with buttons. I see how this can be useful for a user who understands the app fully but as a first time user it was very confusing

**Comment by Red6785** [comment]
Perhaps a first-time user option tutorial to show them where features are. I'll admit that I don't actually know where lyrics are myself..

**Comment by MSOB7YY** [comment]
@Joeeeeb5 so u mean u were also confused with poweramp, i also did, i can imagine someone a bit confused first time using namida, but i tried making things as straightforward as possible, want music playback only? sure just click on song, played!
want to do something for the track? (edit tags, view album, artist, play next, play last, etc,) click on menu, see what u want, done!
in my opinion u can get the full experience just with few days spent on the app, u cant expect to experience every single feature on the same day 

1. video/audio switcher works if you have local video linked to the music, or a youtube link in track comment tag, dont skip the readme https://github.com/namidaco/namida#video-integration
2. online caching works if fetched video from youtube, or if u just played video on youtube itself, open search icon and search for something on youtube and play
3. album art animation is enabled by default, u just see it animating lmao, want to turn if off? go to customization settings
4. i dont see where are those lot of buttons, but bothways ignore them, they are there for who need them. 

- lastly i personally prefer my app/the app that i use to have all the possible functionalities i might use one day, even tho i dont use/understand some of them, its far better than an app with little-to-no functionalities at all

-------
@Red6785 
where do u want them to be? i would guess u want them in miniplayer so u can switch easily? well yeah the icon beside the queue icon in bottom right is the lyrics, toggle it.
right now its not so reliable since it fetches from google 🤡, but the lrc support is almost done and can fetch synced lyrics from database

**Comment by Red6785** [comment]
By a user tutorial I meant more like a recorded video that just showed where most main features are, and when you opened the app for the first time, it linked you to it. Also, where do the lyrics show up? I wrote the lyrics in manually but I can't actually find them when I toggle it is what I mean.

**Comment by Red6785** [comment]
![Screenshot_20231012_165622](https://github.com/namidaco/namida/assets/88458171/b7a158cc-bf2a-4531-bb94-2dcbda114b88)
Both of the lyrics options don't make them pop up.

**Comment by MSOB7YY** [comment]
yeah still tutorials would be time and effort consuming and adding videos will increase app bundle size, BUT im planning to publish some tips from time to time on telegram/discord

------

till v1.3.0, lyrics were only fetched from google (and i forgot about embedded lyrics tehe), now I've implemented full lrc support, matching goes as following (by order):

- LRC (Synced)
  1. Device LRC (.lrc file exists in same directory)
  2. Cached LRC (.lrc from previous downloads)
  3. track embedded lrc
  4. database (requires internet)
- TXT 
  1. Cached txt (from previous google search)
  2. track embedded txt
  3. google search (requires internet)


everything is done automatically, but u can edit them (put ur own lrc file or remove previously added ones)

------

synced lyrics editor may be a thing but not in the next release
