### ISSUE TITLE
[ISSUE] make lyrics searching easier

### ISSUE THREAD

**Issue by aneesh1122** [namidaco/namida#174]
1) When I write the name of the song in the lyrics search bar and press enter, it takes me to the next line

2) The song's title is not editable. The app makes us write the whole song's name while searching for lyrics.

## Expected Behavior

1) I expected it to search the lyrics whenever I press enter. 

So, after writing the name of the song I have to press back button and then select the 'search' button which works but it's more convenient to press enter and get the lyrics results.

2) I expected to be able to edit or modify the existing song's name
## Screenshots

![IMG_20240414_121137.jpg](https://github.com/namidaco/namida/assets/45353488/a693e928-a020-4de8-9026-0132f072a7de)

**Comment by MSOB7YY** [comment]
ur probably right that's definitely more convenient, gonna check immediately

**Comment by MSOB7YY** [comment]
as referenced:
1. 'enter' button will search instead of new line
2. unfortunately, u will need to press a small icon to imprint the text and be able to edit, thats because the default search is achieved by obtaining the exact lyrics for the artist & title, whileas searching just searches the query which should have lower matching compared to the first approach.

https://github.com/namidaco/namida/blob/bb27bf384003e2c09d24fff0693d4e277a7892c7/lib/controller/lyrics_controller.dart#L199-L209
