### ISSUE TITLE
[ISSUE] no size settings for player buttons (playlist, lyrics, equalizer)

### ISSUE THREAD

**Issue by nuser222** [namidaco/namida#192]
Hello,
my big fingers have a problem to hit the correct button. The curved display of my android smartphone makes it even worse. Is it possible to implement an setting for icon size and spacing?

## Screenshots
![nami](https://github.com/namidaco/namida/assets/169761159/3876ae39-14e2-44d0-9b19-674a091572e3)

would be cool if possible because otherwise the player is almost perfect but this makes it unusable for me
)))

**Comment by MSOB7YY** [comment]
uhh is it really unusable? the buttons may look small but they have decent hittest around it (around 48 pixels iirc) which is like most action buttons out there in other apps

im not against extra settings but allowing to customize miniplayer dimensions will make it a mess, the only way is maybe make them a bit bigger but again is it worth the design vs usability? like sorry i dont know how big finger affects it, i tried using my whole thumb and it still hit the nearest button normally so what is the actual issue for it?

**Comment by MSOB7YY** [comment]
i really keep trying to reproduce but buttons already have a good hit-test

icon size 20px vs 22px.. looks awful tbh
![image](https://github.com/user-attachments/assets/2a9e2010-0e09-4d87-a98d-bcf64dcb5817)
![image](https://github.com/user-attachments/assets/6497900c-a108-4039-8fe2-2888bb8eea61)

i ended up increasing the padding a liiil bit (+2px vertical & +4px horizontal), which doesnt affect look but may help. sorry this is like the most i could do, otherwise the spacing is just too much

changes will be in v4.0.9 or higher https://github.com/namidaco/namida-snapshots/releases/
