### ISSUE TITLE
[QUESTION] Musicolet somehow sounds clearer than Namida, possible?

### ISSUE THREAD

**Issue by nuser222** [namidaco/namida#194]
When I play a flac file the sound seems to be better with musicolet in both players no effects or equalizers are activated

However, musicolet's own encoder is selected in the menu. Is it possible that Namida uses the system encoder and that makes a difference in terms of sound?

**Comment by MSOB7YY** [comment]
yep totally. namida just uses exoplayer with its default encoders, which i guess defaults to system encoders. musicolet might be using ffmpeg to play or other custom encoders. unfortunately it's not smth easy to implement nor have i the experience with audio decoders/etc, and it's not the main focus in namida. sorry for that

you can compare sound in namida to YouTube/YouTube music, since both use exoplayer too
