### ISSUE TITLE
[FEATURE REQUEST] More options for MV matching and more

### ISSUE THREAD

**Issue by Lionharth** [namidaco/namida#204]
I am trying to watch the MVs of Loona 1/3 because I have all of their songs and MVs downloaded, but it doesn't get matched since the video file name is "Loona 1_3." So, I'm not sure if it exists, but I'd love to have the option to manually select which MV to match the MP3 to and to have more options for auto-matching, like if it can't be found, try to only find by title, etc. Thank you very much! I absolutely LOVE the app!

**Comment by Lionharth** [comment]
Also I forgot to say but I also have some other issues with MVs not being found because of the artist, for example I was trying to watch Heart Attack by Chuu and the mp3 is set as Heart Attack by Loona because that's how it is on streaming but the mv just says chuu so basically the same issue

**Comment by MSOB7YY** [comment]
thank u for loving it! hmmm can't you make both files have the same name? matching is done by filename first, then title + artist as fallback iirc.
i dont feel like manually linking videos cuz things will get quite complicated so idk

![Screenshot_20240519-233210_Namida](https://github.com/namidaco/namida/assets/85245079/c9ccd0d4-3701-4505-ba78-d7efd3e2d618)
here the options are (auto, filename, title & artist)

also i dont remember properly but i think long pressing video button in bottom left can allow u to choose which video to pick (if there is more than one)

so anyways isn't it possible to change filenames? (at least for the music files, since they already got their own tags inside)

**Comment by Lionharth** [comment]
> thank u for loving it! hmmm can't you make both files have the same name? matching is done by filename first, then title + artist as fallback iirc.
> i dont feel like manually linking videos cuz things will get quite complicated so idk
> 
> ![Screenshot_20240519-233210_Namida](https://github.com/namidaco/namida/assets/85245079/c9ccd0d4-3701-4505-ba78-d7efd3e2d618)
> here the options are (auto, filename, title & artist)
> 
> also i dont remember properly but i think long pressing video button in bottom left can allow u to choose which video to pick (if there is more than one)
> 
> so anyways isn't it possible to change filenames? (at least for the music files, since they already got their own tags inside)

Ah okay, I'll just do that then😊
