### ISSUE TITLE
[FEATURE REQUEST] Import playlists from file 

### ISSUE THREAD

**Issue by SpiralUniverse** [namidaco/namida#217]
as the title suggests a small feature to be able to read data from a file and generate a playlist 
for example m3u8 file that contains all data for a playlist from how many songs and songs names to the order they are in
this would be really helpful 
especially cz i switched to namida 2 days ago i have 1600 songs and playlists that contain huge nb of songs i dont want to go to each playlist i had and recreate it in namida adding each song 1 by 1 (its painful)
please consider this feature and close if your not gunna work on it
thanks in advance ☺

**Comment by MSOB7YY** [comment]
dude thats already a thing ☠️ make sure the **folder** containing these m3u/m3u8 **is inside indexer folders*. then just refresh playlists page or restart namida.
you can also open any ".m3u" file and share it to namida, it will be added to the queue directly. (soon will add .m3u8 files)

if this ain't working properly for you, then pls send a sample file & the logs

**Comment by SpiralUniverse** [comment]
okay ive tried what u have said i didnt quit work as expected but did work eventually 
i tried to refresh and re-index after i made sure that the Okay.m3u (i didnt name it that way) was placed under 0/Namidia/M3u Playlists which is generated automatically after i did try to generate playlists randomly! but no playlist called Okay was created in the app
I then tried to create it and re-index and refresh but nothing happened (btw i have no idea about the difference btw refresh and re-index) 
then what i did i playing a single song , go the queue remove it (the app suddenly got white color filter which was as if it crashed but it was fully functional ) then going to the m3u file and open with namida worked as u said it should all the songs was in the queue followed by select all and add to playlist thats how it worked!
thanks for the tips , sorry for any miss-understanding 
i tried too recrate the white screen described above  but it didnt work!

**Comment by SpiralUniverse** [comment]
also since the logic is already available (dont know if u had that planned) isnt it better to add UI related to import such files even if they where outside the folders added to the indexer by making user select where the m3u file is located?

**Comment by MSOB7YY** [comment]
pls send logs from settings -> about, this will tell what went wrong and will tell also about white screen

idk i feel like its over complicating it, automatically importing is way better, if you want to manually import m3u playlist outside the folders, then just share to namida and do whatever u want next. also there is no place left for such a button

**Comment by utopologist** [comment]
Hey, I'm having pretty much the same problem. I can't get any other playlists into the app. I've tried opening the m3u files with the app, moving them into the indexed folders, adding new indexed folders, etc. Nothing seems to work. I've attached my log files. Otherwise, lovely program!

[logs_2.5.6_240522118.txt](https://github.com/user-attachments/files/15920292/logs_2.5.6_240522118.txt)
40522118.txt
[logs_tagger_2.5.6_240522118.txt](https://github.com/user-attachments/files/15920287/logs_tagger_2.5.6_240522118.txt)
…]()

[logs_clean_2.5.6_240522118.txt](https://github.com/user-attachments/files/15920284/logs_clean_2.5.6_240522118.txt)

**Comment by MSOB7YY** [comment]
@utopologist thank u so much for the logs, the error is identified now. fixing rn

**Comment by MSOB7YY** [comment]
@utopologist can u try the latest beta from here https://github.com/namidaco/namida-snapshots/releases ?, i think its already fixed there

**Comment by qoished** [comment]
> pls send logs from settings -> about, this will tell what went wrong and will tell also about white screen
> 
> idk i feel like its over complicating it, automatically importing is way better, if you want to manually import m3u playlist outside the folders, then just share to namida and do whatever u want next. also there is no place left for such a button

You can add such a button under "Create Playlist". Upon pressing that instead of having a pop up for the name, you can have it create a list pop up with options "New Playlist" and "Import Playlist". To be honest I've never seen a music player (I tried a lot of them) that has this auto import and doesn't have a button or option in settings at least for it. It's more natural to have an import option rather than auto importing from a folder. Or you can have both.

**Comment by MSOB7YY** [comment]
@qoished thank u so much <3, thats actually a nice idea but at the same time its kinda annoying having to add each playlist manually, and i cant think about a button that adds a whole folder cuz that will be just the same as indexer folders.. idk might rethink about this

**Comment by qoished** [comment]
@MSOB7YY I appreciate your kind response! <3 We all love your work! Keep it up!

I see your point there, that importing a folder is purposeless since it's a feature that already exists in a different form. Although you could use the default system file picker to import the files/playlists.
That way the user can select multiple files from a folder but isn't required to pick either all of them (the whole folder) or only one playlist (one file).
This will make it so the user can import specific files that are in one folder or files from different folders. Also the use of the default system file picker will grant the user the ability to even import playlists from the drive or other cloud service (that are uploaded from a different device).
Also please take in mind that by importing files to the app (Namida) will also grant the user the ability to erase the exported files from his immediate directories (ex. Music folders, Downloads, etc.). I take myself as an example since I have more than 60 playlists that I exported from my other music player (Poweramp).

I respect any decision you make as a developer and by all means don't want to force you to integrate a feature that you think is unnecessary.
I may work on the app myself in my free time if I find any xD and will try to implement this feature and make a pull request if I find the chance.

Again, thanks for creating this beautiful app! 
Love <3
Jonathan

**Comment by MSOB7YY** [comment]
@qoished mughagaha thank uu and i love yall <3

i understand your point and its totally valid (about importing manually) but u mentioned "erasing" exported playlists after importing to namida? that seems so off to me tbh, m3u playlists are meant to be universal, when namida reads an m3u playlists, it doesn't make a copy but rather actually interact with the file itself, which allows for editing the file from anywhere and that edit will be reflected everywhere (in all apps).

all players i used did *automatically* read m3u playlists saved on device (typically in `storage/emulated/0/Music`) and allow interacting/editing the same way namida does, so it should be also a known thing. 
   - if you had to add the folder manually, this means that namida tries to help you, u should be actually saving the playlist in the `Music` folder in the first place
   - if you dont want some playlists to be added, thats also a strange thing, why have them in the first place? yet namida also helps u u can put in a folder outside indexer folders, or add the folder to the blacklist

again allowing to add playlists manually is a nice idea but really pointless, as per every player i used and per how m3u playlists should be treated

lemme know if u have a different take on this ^^ i might be wrong ^^ ([*btw building is currently not possible*](#37)

**Comment by MSOB7YY** [comment]
i realized now that u may have exported these playlists just to be able to **switch to namida**.. now that really should be a thing lmao

**Comment by qoished** [comment]
@MSOB7YY yeah I did export them so I can switch from Poweramp.
Well my playlists are m3u8 xD and still can't use this feature lmao. Although yeah basically I'm switching from another player and don't really need to have them as files in my non Android/data directories.
Although yeah I'm trying to find a music player that is open source and better than poweramp which is closed source and paid. And I have high hopes for your app. So far I've liked mostly everything. I'm just waiting for the m3u8 integration so I can test it side by side with my current player

**Comment by MSOB7YY** [comment]
@qoished just allowed this, a popup to import playlists that can be used only by namida (u can choose files or folders), and the option to auto import m3u is now toggable, all from playlists page
available with beta v3.7.3

thanks for suggesting ^^

**Comment by aausshhhh** [comment]
![Screenshot_2025-05-13-16-02-37-38_efbfb0790a8187cbd43560835da1b509.jpg](https://github.com/user-attachments/assets/470b8c96-9148-46f2-82bf-5dbe4d381a19)

I uploaded the m3u file and it shows this

**Comment by MSOB7YY** [comment]
@aausshhhh ur m3u file has a url-encoded file paths, its the first time i see something like this, which app did u use to export that m3u?

**Comment by The-Unsticker** [comment]
All players seem to have a problem with the following M3U playlist on Android 12.  It seems to be a bug because only the music files with spaces in their names fail.  Yet they work fine on playlists without the Icelandic characters.

https://pastebin.com/paBsuYy4

Worked fine on Sailfish (Linux).  Phone is an Xperia 10 iii.  List was made with MP3Tag.

**Comment by The-Unsticker** [comment]
Another playlist Namida can't cope with.  I think it doesn't like files being in different subdirectories in the playlist pre-conversion.

https://pastebin.com/FhwZ2Gmn

**Comment by MSOB7YY** [comment]
not any text can be considered a playlist, please create the playlist in **m3u** format, that's how playlists should be shared between apps/devices

and as for the previous comment I really got no clue except that some paths seems malformed (has weirdly encoded character), which won't work later when trying to access that path

**Comment by The-Unsticker** [comment]
> not any text can be considered a playlist, please create the playlist in **m3u** format, that's how playlists should be shared between apps/devices

Oh?  What's wrong with it?  I don't know much about the M3U format.

But they're both M3Us, created by MP3Tag.  And Playlist Creator 3.62 created an identical one (relative paths and "extended info" disabled).

The M3U playlist is imported, but none of the tracks play.  I can redirect to each track manually where the playlist says it is but it's very inefficient.

**Comment by MSOB7YY** [comment]
@The-Unsticker nvm there was a small issue i just fixed (it was adding extra path separator before path, which should not be there on windows)

just fixed now and the playlist has valid paths now

<img width="396" height="679" alt="Image" src="https://github.com/user-attachments/assets/5cf6d1a0-66e7-4760-8bdd-142dc72b7772" />

also improved a bit to ensure path separators are resolved properly on different platforms

**Comment by The-Unsticker** [comment]
Many thanks!  Tested and works.

The issue with the Sigur Ros playlist is that whatever Namida is using to read & parse it simply cannot cope with Icelandic characters like ó.  As I said, this is common to all players on Android 12, so no fix expected.  Phone is a Sony Xperia 10 iii.
I apparently have to brute force to Android 13 but whether that will help I don't know.

**Comment by MSOB7YY** [comment]
@The-Unsticker i see, maybe android can fix in a newer release, cuz i don't remember having such issue on A11

**Comment by The-Unsticker** [comment]
> [@The-Unsticker](https://github.com/The-Unsticker) i see, maybe android can fix in a newer release, cuz i don't remember having such issue on A11

I finally got around to upgrading to Android 13.  It's apparently better for handling Unicode filenames but didn't fully fix the problem (not coping with lots of weird Icelandic characters). What did fix it was changing the playlist encoding to UTF-8 (not ROM).  Suggestion was by ChatGPT 5.5.
