### ISSUE TITLE
I get that you like anime but...

### ISSUE THREAD

**Issue by forbygrace** [namidaco/namida#218]
Intended as constructive feedback: The app icon is just a little bit, um, out of character with the rest of the app's caliber, quality, and design. While I think it's a nice picture, I think that it doesn't fit as an app icon. Maybe it could still find it's way into the app somehow without being the central icon image the app is known for? You made a lot of intentional fantastic design choices in this app. The UI and UX are fantastic and there's really a good thing going here. But if anime is not the user's "thing" as in my case, it's a slight turn off I have to admit. A simple graphic would do much better in my humble opinion and keep the app crisp, clean, and polished in every respect. Thanks for all your hard work!

**Comment by l300lvl** [comment]
(disclaimer: I'm not affiliated with app in any way other than being it's fan boi)

As someone that has over 300 apps installed at most times, I understand the frustration, however. It's also a bit nuanced in that any modern user is typically using one of any hundred common launchers which allows you to set your own icon.

If you're using a stock launcher you're really doing your own well being a disservice as most of them were built with a group of people in mind, not an individual. As an individual we choose android because of choice and for that reason, the designers of millions of apps on play store (which this isn't) have way too many choices to make to try and please everyone(which is a hive mentality)

I therefore wish you peace in any resolve, but suggest you check out some launchers that allow for custom icon packs and therefore, changing individual icons.

As an individual I would highly recommend Smart launcher. It makes me warm and fuzzy and has tons of fancy edges too.


Alas, sorry I ranted. Such is the state of living in a free world.

**Comment by z9xx7o0** [comment]
@forbygrace  you can manually change the app icon because this app is **OPEN SOURCE**, and the picture in the back is located in: 
storage/emulated/0/Android/data/com.msob7y.namida/files/Artworks/ARTWORKS.NAMIDA_DEFAULT_ARTWORK.PNG
Where you can also manually change it.

- **IMPORTANT** If you are on android 14 or higher,  you need to use the stock android file manager to access those files. To use that file manager, you can use some apps. Here is an example: 
https://play.google.com/store/apps/details?id=com.marc.files

- If you are not familiar with how android apps work and want to change the icon, you can use some tools like "apk tool m"

**Comment by MSOB7YY** [comment]
thank you for feedback
1. icon is opinion based, some like it and others don't i know that
2. i suck at designing, and i aint paying for a designer to create icon
3. most apps already have icons that resembles music, there is no really much left for namida to use
4. i personally prefer the current icon, which means even if there were any other choices, it may be included as optional

so basically its quite not possible to change the icon currently, but may be in future if there were better alternatives

**Comment by MSOB7YY** [comment]
@z9xx7o0 shii chill man its not fully open source so he aint building shi☠️

the artwork in that path is only used as a fallback for notification, that doesnt change the app icon or the other places its used in.

apk tool might be a better option, tho i think it would produce other issues

**Comment by z9xx7o0** [comment]
> @z9xx7o0 shii chill man its not fully open source so he aint building shi☠️
> 
> the artwork in that path is only used as a fallback for notification, that doesnt change the app icon or the other places its used in.
> 
> apk tool might be a better option, tho i think it would produce other issues
> 
> as @l300lvl mentioned its best to use a launcher that supports changing icon or just get used to it like u get used to many things forced upon you >.<

You can tell I never tried changing it XD. I don't care what the icon is or the background is. The app is already amazing.

**Comment by forbygrace** [comment]
I just want to clarify a few things. First: @MSOB7YY you clearly do not suck at designing. You've made a fantastic app and should be proud of it. You don't need to pay someone to make an icon. That much is obvious. You're entitled to prefer the current icon and keep it. That's your choice. But realize that my 

I knew people were gonna get their panties in a wad over this and say dumb stuff like "if you don't like it change it yourself." Which is totally missing the point of my original post. I could change the icon myself if I wanted to easily but I shouldn't have to. I have concerns with using alternative launcher since they literally override every android security function. 

I feel like I was fairly objective actually in my original statement. I was simply saying it is a bit incongruent with the rest of the app and the function it serves. An icon should be simple representation by default. Those statements are not personal preference, they are statement of fact and a widely accepted UI design principal. If folks wanna anime-ify their phone, I say go for it! That is an example of personal preference. But when an icon becomes something I have to explain to my wife after handing my phone to her and she says "oh, what the heck is that? Are you into anime now?" it just kinda shows it's not that universal. It's not that I'm embarrassed by the situation at all; I'm fine explaining it. And I could change the icon myself, you're right. I'm just trying to provide feedback that might make the app just that extra notch more stellar and universally acceptable. That's all. 

Thanks for the awesome app. Throw my feedback in the trash if you want to. It won't hurt my feelings. The app is great even if the icon doesn't quite fit. I'll still use it.

**Comment by MSOB7YY** [comment]
@forbygrace thank you again for understanding, what i meant by designing is like designing icons which im not good at. i had an old icon and it was just "music note" with gradient background. was too boring tbh that's why i want smth new that's not lazily used by almost every other music app. 

i get your point that the icon might not match with the rest of the app, but again i want smth unique and catchy, despite strictly following rules. i always do that as seen in the rest of the app too 

and ur feedback is totally valid and makes sense, its just that its smth i wanted to do and i wont change it to appeal more people or become universally accepted or etc, hope u understand my pov 🌺

**Comment by forbygrace** [comment]
I do get it. It's not a hideous icon at all. Actually looks quite nice and definitely unique. It matters to you and that's totally ok! Again, thanks for all your hard work.

**Comment by MSOB7YY** [comment]
@forbygrace thank u sm for understanding! 💖

**Comment by qoished** [comment]
@MSOB7YY personally I love anime!
If I take the current icon and try and make her hold a player icon would you consider using that?

**Comment by MSOB7YY** [comment]
@qoished cant say before i see lmao but tbh i like the current one so other alternatives *might not* get used.. idk
