### ISSUE TITLE
[FEATURE REQUEST] show Releases tab playlists on artist's page on youtube 

### ISSUE THREAD

**Issue by litgub** [namidaco/namida#247]
Albums/songs that aren't uploaded by the artist as videos don't show up on the artist's channel

Add a feature that lets users view the Releases tab on youtube when you click on the channel you searched for 
or integrate albums from the release tab on the artist's page

**Comment by MSOB7YY** [comment]
thats for "topic" channels right?

**Comment by MSOB7YY** [comment]
woah forgot about this issue lmao sorry, this is done for a while now. 

all channel tabs excluding community/store are now accessible (home, live, shorts, releases, playlists, podcasts, etc) and about section too since v3.9.2

**you can download the latest beta v4.0.8 from here https://github.com/namidaco/namida-snapshots/releases/**
