### ISSUE TITLE
[BUG]  When I set a new playlist the keyboard of the phone disappear after 1 second spawning, leaving me with the impossibility to create a playlist and save my music

### ISSUE THREAD

**Issue by purple-trollface** [namidaco/namida#249]
https://github.com/namidaco/namida/assets/118052423/db64b8ca-14e6-4b8c-8459-3d0fbebc51d1

Uploading mobizen_20240630_231406_001.mp4…

## Steps to Reproduce

1.
2.
3.
4.

**Comment by purple-trollface** [comment]
I resolved but one thing, on the playlists menu you should put the possibility to add songs from YouTube, and not only locally

**Comment by VerySweetBread** [comment]
Bro, it's a player for local music

**Comment by MSOB7YY** [comment]
its sort of fixed in beta bothways.
about your suggestion, no, local playback and youtube are separated. mixing them is kind of impossible taking in consideration the implementation of various parts for both local files & youtube videos

u gotta download a yt video/audio first if u want to add them to a local playlist
