### ISSUE TITLE
[FEATURE REQUEST] m3u import and export favorites and playlists

### ISSUE THREAD

**Issue by Shahinol** [namidaco/namida#253]
I really love your app, it's perfect in almost every way but one.

I find this feature indispensable honestly, m3u import and export for local playlists and favorites.

Almost all apps have it, but musicolet and oto player are particularly effective at it from my experience.

Thank you again

**Comment by MSOB7YY** [comment]
m3u files are automatically recognized, as long as the m3u folder is inside indexer folders, although there was a bug in stable version that prevented them from showing up, and [is fixed in beta](https://github.com/namidaco/namida-snapshots/releases).

there is a related talk which suggests importing files instead of just reading/editing in place #217

thank u so much for loving it tho <3 it loves u too
