### ISSUE TITLE
[ISSUE] Can't open audio files from Google drive

### ISSUE THREAD

**Issue by Adzegd** [namidaco/namida#263]
Tried opening a .wav file from Google Drive but the app keeps saying "Empty file" and also are .flac & .wav formats not supported in YouTube downloads?

**Comment by MSOB7YY** [comment]
unlike most apps out there (if not all), we completely discard android content provider and try our best to retrieve the actual file path, which means it will not work with remote services like drive.
this is done for many reasons but most importantly, to eleminate unneccessary file caching (which is saved in app data) and to keep ur things organzied by forcing you to download it somewhere first. using and relying on a cached version is not ideal so we put that aside.

youtube audio formats are ONLY **mpeg (acc)** and **opus** put inside **m4a** and **webm** containers. youtube does **NOT** provide flac or wav.
there is a button to show webm formats if available (next to x icon shown below), but its not really recommended, they may or may not have better bitrate/quality but they are terrible with tagging. m4a is the way to go unless otherwise.
![image](https://github.com/namidaco/namida/assets/85245079/a8d53055-b4aa-445b-b713-c21e959e01a1)
