### ISSUE TITLE
[QUESTION] • What's Obso and Obx0

### ISSUE THREAD

**Issue by iSaqibShafique** [namidaco/namida#281]
What's obx0 and obso, is it the refined version of GetX or something?

**Comment by MSOB7YY** [comment]
they are part of the package https://github.com/MSOB7YY/nampack, which is a just a reactive library.

the naming is affected by getx since the project used to depend on it earlier, however the implementation is quite different. 
anyways, 
- `Obx()` works like `Obx()` in getx. both automatically register & dispose any reactive value.
- `ObxO()` is just a StatelessElement that registers `rx` argument in `StatelessElement.mount` and removes it in `StatelessElement.unmount`, its considered as more performat than `Obx()` (even if a little bit)
- `obso` is an extension that initializes `RxO<T>`
- `obs` is an extension that initializes `Rx<T>`
```dart
extension NamReactiveUtils<T> on T {
  Rx<T> get obs => Rx<T>(this);
  RxO<T> get obso => RxO<T>(this);
}
```
- `RxO` instances can be used only with `ObxO`
- `Rx` can be used in `ObxO` and `Obx` since it exposes additional getter `valueR` which automatically registers the class
```dart
 @override
  T get valueR {
    RxNotifier.pullObservers(_updaters!);
    return super.value;
  }
 ```
- the `O` in `RxO` and `ObxO` stands for `Optimized`

hope everything is clear for you ^^
