### ISSUE TITLE
Progress bar not synchronized 

### ISSUE THREAD

**Issue by fedikhatib** [namidaco/namida#34]
When playing an audio the progress bar is not synchronized with the elapsed and passed time and not showing the position in the slider. And when taping it pause the player.
Also if you notice in the right side of the progress the time is 00:00
![Screenshot_2023-10-24-14-41-39-891_com msob7y namida](https://github.com/namidaco/namida/assets/34138112/72e0b6e7-ac0e-4afd-aee9-20e12aaad6c4)

How to reproduce:
Go setting and reindex and refresh library .
The open audio from the recent home

**Comment by Red6785** [comment]
Had this issue suddenly, never noticed it before, but 
![Screenshot_20231024_133854](https://github.com/namidaco/namida/assets/88458171/59297019-c8e5-4138-8d77-be158f0fc770)

**Comment by MSOB7YY** [comment]
this happens because the duration is zero, i.e. couldn't be extracted

usually when u play a track, and it has a duration of 0 (tagger failed to extract duration before), then the new duration obtained (after playing) will be assigned to this track

what happened here is either one of these:
1. the player also failed to obtain a duration (less likely)
2. u did a reindex, which erased the duration obtained from player, and now u have to play it again to assign the correct duration

**Comment by MSOB7YY** [comment]
@Red6785 what issue exactly? the screenshot seems alright

**Comment by Red6785** [comment]
@MSOB7YY as you can see, the duration of the song is 3 minutes and 22 seconds, yet the progress bar is halfway through at 57 seconds. It should be halfway at 1 minute and 44 seconds.

**Comment by MSOB7YY** [comment]
as mentioned, this should be fixed (hopefully), feel free to re-open otherwise.
