### ISSUE TITLE
Feature Request - Set As Ringtone

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#4]
Musicolet has a feature that allows you to set a song as your ringtone in the app if you have it downloaded locally. I think it's a good feature that deserves a home here, too.

**Comment by MSOB7YY** [comment]
Alright, although there is really no more place inside track dialog so it will live inside `advanced`.. forever and ever

**Comment by NikunjKhangwal** [comment]
+1
@MSOB7YY Isn't it possible to make the dialog scrollable?

**Comment by MSOB7YY** [comment]
@NikunjKhangwal 
it is already? but the whole thing is scrollable, not just the middle items
-----
update: this one is taking quite a while, the permissions needed to modify ringtone etc is pain, i would need to work on the native side myself

**Comment by NikunjKhangwal** [comment]
No, i was talking about the three dot menu list where "advanced" button is since you said there isn't enough place for a set as ringtone button. Not the song metadata list that appears when you click on Song name.

**Comment by MSOB7YY** [comment]
@NikunjKhangwal 

oh what i mean by "no enough space" is that dialog can get bloated with items, which uhhh- gets annoying to look at 

there are few items (3-4) that appears on demand depending on the track itself, so having another item there always is just a bad idea

imo its a good place in "advanced", one doesn't constantly change their ringtone

**Comment by MSOB7YY** [comment]
@NikunjKhangwal 
ofc u can! it wont be the first time to suggest something u not gonna see 💖
what are them?

**Comment by NikunjKhangwal** [comment]
Equalizer Button (This could lead to system equaliser since the app doesn't have one of it's own OR a third party one if installed). This is something people use often.
Second was a sleep timer button, i thought it would be easier to use than sidebar but on a 2nd thought both take about the same effort so just ignore this one. If you make audio info appear in two line as mentioned in #50 then consider adding sleep timer button before repeat button when there's enough space.
