### ISSUE TITLE
[BUG] YouTube videos not working

### ISSUE THREAD

**Issue by Bilal-ALi69** [namidaco/namida#432]
## Expected Behavior
You click on a video in YouTube and the video plays 

## Current Behavior
Not all, but majority of the videos show an error in playing the video, and some don't even play the audio and skip to the next

## Steps to Reproduce

1.Open Namida and click on YouTube in the     status bar
2. Search up a video (making sure to tap on the 'online search' mark)
3.Tap on the video to be played.

## Screenshots
![Screenshot_2024-12-22-10-05-46-529_com.msob7y.namida.png](https://github.com/user-attachments/assets/f5832027-ce4b-400d-80ab-8746d64b2c0f)

![Screenshot_2024-12-22-10-05-14-911_com.msob7y.namida.png](https://github.com/user-attachments/assets/bda3bea6-de52-43fb-8c27-f4cd9bcda21d)

## Logs
https://drive.google.com/file/d/10BL6L7dVg7_jRQlHm9KOw6X0jCcprIMk/view?usp=drivesdk

## Possible Solution
Don't know coding, but hoping that the problem is fixed as soon as possible.

**Comment by D14FR25** [comment]
I have this big issue since 24 hours, after YT began the atack agaisnt adblockers. Now even wit adblockers disabled /uninstaled, even on a new fresh inwtall of Waterfos web browser, on Chrome, and Brave, get ads, and then the black scren and spining wheel. Only obsolete Firefox still working. Besides, WinW YT downloader is unable to download YT videos (but works with FAcebook or otehrs), only cobalt is now able to download vieos from YT on this computer. system Windows 10 updated. Reboot, clearing cacjes, nothing works. Please help !!! I just found your post googleing ... Others seems to have issues with YT after reports on reddit.

**Comment by MSOB7YY** [comment]
@Bilal-ALi69 @D14FR25 issue was resolved in **v4.8.3**
https://github.com/namidaco/namida-snapshots/releases

if u frequently face "Error playing video", then clear the audio & video cache using that button

**Comment by Bilal-ALi69** [comment]
> @Bilal-ALi69 @D14FR25 issue was resolved in **v4.8.3**
> https://github.com/namidaco/namida-snapshots/releases
> 
> if u frequently face "Error playing video", then clear the audio & video cache using that button

The error occurs in version 4.8.3 beta, and I have tried clearing the following caches, but it only has made the problem worse, as those videos, whose audio was at least playing, now they just get skipped over.

**Comment by MSOB7YY** [comment]
thats so random, u need to clear both audio & video cache
also make sure ur on v4.8.6+
