### ISSUE TITLE
Lrc file isn't getting picked up automatically

### ISSUE THREAD

**Issue by NikunjKhangwal** [namidaco/namida#46]
I have both the music and lrc file saved in same directory with same name.
![IMG_20231101_150233](https://github.com/namidaco/namida/assets/99175083/37d4f78e-ecec-4628-bf47-64cd38c14d1d)
However the app didn't scan for the lrc file automatically after i refreshed the library. I have to manually select it from my file explorer
![Screenshot_2023-11-01-15-03-07-291_com msob7y namida](https://github.com/namidaco/namida/assets/99175083/bb81c4e0-cd20-498b-9eba-64e5f3da71b7)

**Comment by MSOB7YY** [comment]
oh thanks for the notice, by default lrc in the same directory is preferred over fetching

the issue here is that the lrc file name should have the full name of track
https://github.com/namidaco/namida/blob/8fe2959d6d6fe7bbaa29276860dc4bd9718632b4/lib/controller/lyrics_controller.dart#L80
 (in ur case, it should end with `.m4a.lrc`

- will push a fix to also include files like yours

**Comment by MSOB7YY** [comment]
should be fixed with 20cb6386baba1624167e90ce0a9fa8dfff168176, thanks for reporting 🌺
