### ISSUE TITLE
Bug and enhancement

### ISSUE THREAD

**Issue by Shivamhobbyist** [namidaco/namida#50]
![Screenshot_20231107_113253.png](https://github.com/namidaco/namida/assets/78287172/cfe8cb24-536a-4547-a44d-b95f83e1f5fb)

![Screenshot_20231107_110500.png](https://github.com/namidaco/namida/assets/78287172/cb34fe73-3e75-4259-a2a9-464302a0264a)

![Screenshot_20231107_110316.png](https://github.com/namidaco/namida/assets/78287172/9482e046-452c-4bfa-8f41-60f11101cd50)

Fix all

**Comment by MSOB7YY** [comment]
1. investigating
2. was fixed
3. not possible, u can swipe to the right a bit to have a peek
4. maybe its time to reduce font size a bit from Customization Settings, i cant make it take more than 1 line

**Comment by NikunjKhangwal** [comment]
Can Confirm, expanded lyrics button doesn't work a lot of times for me as well. Also yes make the audio info take two lines if it's overlapping. You can also move the repeat button above queue button since there's enough empty space along with a new "sleep timer" button above lyrics button. (Was going to make a new feature request for sleep timer button)

**Comment by MSOB7YY** [comment]
@NikunjKhangwal 
after investigating, it seems like the issue is caused by scaling the artwork (`AnimatedScale`) which might not allow touches outside the original size.

im not very sure about workarounds, there isnt any place for this button in the miniplayer ui

about making the info 2 lined, and possibly introduce sleep timer (by making 4 squared icons), it will require some painy refactor and i don't think it will even look good, especially the 4 squared icons

ughhh im not sure yet

**Comment by NikunjKhangwal** [comment]
Yeah, fair point. You should at least make the info take 2 lines tho since that overlap doesn't look good either.
Also unless i'm missing something, why do you call the main playing screen "miniplayer"? I thought miniplayer was the one that appears when you swipe down the main player (With only back play/pause and previous button). I'm going to create a issue for this and i don't want it to be confusing.

**Comment by MSOB7YY** [comment]
okay i will look into that after a while

well to be technically right, its exactly "expanded miniplayer", others could work too like player screen or whatever, its just my view, could be wrong.

u can create the issue with any name u like as long as it's clearly referring to it

**Comment by NikunjKhangwal** [comment]
Got it, thanks

**Comment by MSOB7YY** [comment]
with [2031d74bb7c8f06f2c90bbf8ce434f99866d78e8], number 1 (enter lrc fullscreen) can be fixed using 2 ways:
1. since artwork scaling is now possible, u can make it a bit smaller, this will make the button work properly
2. you can also just pinch in (zoom) when lrc view is displayed, and it will enter fullscreen

unfortunately, the core issue (button should be pressed) doesnt seem to be fixable, since scaling up the artwork doesnt scale the GestureDetector hit test area.

for reference: 
1. https://github.com/flutter/flutter/issues/27587
2. https://github.com/flutter/flutter/issues/75747
