### ISSUE TITLE
Possible Bug - Downloading YouTube videos does not seem to work.

### ISSUE THREAD

**Issue by Red6785** [namidaco/namida#8]
I can't find wherever Namida downloads YouTube videos to. It's not showing up in the app, and I can't find it in my files.

**Comment by MSOB7YY** [comment]
downloads are saved to `Namida` folder inside ur internal storage
`/storage/emulated/0/Namida/`
along with 
1. `Compressed` (which saves images compressed from `advanced settings`)
2. Saved `Artworks` (by long pressing inside track info dialog) 
3. Backups

since its saved inside a root folder, it requires `manage all files` permission, now i could save each one in their perspective folders which won't require this permission, but i wanted a place for everything born by Namida
other option would be to use SAF but thats just pain in the ass and not worth it since the project is already open sourced

**Comment by Red6785** [comment]
Ah, I see. Namida doesn't automatically seem to have the ability to pull music from this folder. I'll add it in manually for now.

**Comment by MSOB7YY** [comment]
oh i forgor to add this

**Comment by Red6785** [comment]
Ah, then I'll close this issue and make a new one that specifies the actual problem.
